#!/usr/bin/env tsx
/**
 * Convert Claude Exporter Markdown transcripts to Claude Exporter-style JSON.
 *
 * Usage:
 *   npx tsx backend/scripts/claude-exporter-md-to-json.ts conversation.md
 *   npx tsx backend/scripts/claude-exporter-md-to-json.ts conversation.md -o conversation.cleaned.json
 *
 * Design and conversion decisions:
 * - This targets Markdown generated by Claude Exporter / ai-chat-exporter.net,
 *   not arbitrary Markdown. Expected shape:
 *     # Title
 *     **Created:** ...
 *     **Updated:** ...
 *     **Exported:** ...
 *     **Link:** [...]
 *     ## User:
 *     > timestamp
 *     visible text
 *     ## Assistant:
 *     > timestamp
 *     > thinking summary lines...
 *     visible text
 * - The output intentionally matches the JSON envelope Arc already imports from
 *   Claude Exporter: `{ metadata: ..., messages: [{ role, time, say }] }`.
 * - Message text is reconstructed from the Markdown, not from a paired JSON
 *   file. This preserves visible Markdown formatting such as emphasis.
 * - Assistant "thinking" is treated as a leading blockquote block immediately
 *   after the assistant timestamp. That leading blockquote block is stripped.
 *   Later blockquotes in visible assistant text are preserved.
 * - User blockquotes are preserved. Only assistant-leading blockquotes are
 *   treated as thinking summaries.
 * - The trailing "Powered by Claude Exporter (...)" footer is metadata, not a
 *   chat message, so it is removed from the final message body and recorded in
 *   `metadata.powered_by` when present.
 * - If an assistant section has only thinking and no visible answer after
 *   stripping, the message is preserved with an empty `say` field and a warning
 *   is written to stderr. This is faithful to the transcript boundary without
 *   inventing assistant text.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { basename } from 'node:path';

type ClaudeExporterRole = 'human' | 'assistant';

interface ClaudeExporterMessage {
  role: ClaudeExporterRole;
  time: string;
  say: string;
}

interface ClaudeExporterJson {
  metadata: {
    title: string;
    dates: {
      created?: string;
      updated?: string;
      exported?: string;
    };
    link?: string;
    powered_by?: string;
    cleaned?: {
      source_format: 'claude_exporter_markdown';
      stripped_assistant_thinking_blocks: number;
      notes: string[];
    };
  };
  messages: ClaudeExporterMessage[];
}

interface ParsedSection {
  role: ClaudeExporterRole;
  label: 'User' | 'Assistant';
  time: string;
  bodyLines: string[];
  strippedThinking: boolean;
}

const SECTION_RE = /^## (User|Assistant):\s*$/;
const META_RE = /^\*\*(Created|Updated|Exported):\*\*\s*(.*?)\s*$/;
const LINK_RE = /^\*\*Link:\*\*\s*(?:\[(.*?)\]\((.*?)\)|(.*?))\s*$/;
const FOOTER_RE = /^Powered by Claude Exporter \((https?:\/\/www\.ai-chat-exporter\.net)\)\s*$/;

function usage(exitCode: number): never {
  const stream = exitCode === 0 ? process.stdout : process.stderr;
  stream.write(`Usage: npx tsx backend/scripts/claude-exporter-md-to-json.ts <input.md> [-o output.json]\n`);
  process.exit(exitCode);
}

function parseArgs(argv: string[]): { inputPath: string; outputPath?: string } {
  if (argv.includes('--help') || argv.includes('-h')) usage(0);

  let inputPath: string | undefined;
  let outputPath: string | undefined;

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '-o' || arg === '--output') {
      outputPath = argv[++i];
      if (!outputPath) usage(1);
    } else if (arg.startsWith('-')) {
      usage(1);
    } else if (!inputPath) {
      inputPath = arg;
    } else {
      usage(1);
    }
  }

  if (!inputPath) usage(1);
  return { inputPath, outputPath };
}

function stripBlockquoteMarker(line: string): string {
  return line.replace(/^>\s?/, '');
}

function stripTrailingBlankLines(lines: string[]): string[] {
  const copy = [...lines];
  while (copy.length > 0 && copy[copy.length - 1].trim() === '') {
    copy.pop();
  }
  return copy;
}

function stripLeadingBlankLines(lines: string[]): string[] {
  const copy = [...lines];
  while (copy.length > 0 && copy[0].trim() === '') {
    copy.shift();
  }
  return copy;
}

function stripAssistantThinking(lines: string[]): { lines: string[]; stripped: boolean } {
  let copy = stripLeadingBlankLines(lines);
  let stripped = false;

  if (!copy[0]?.startsWith('>')) {
    return { lines: stripTrailingBlankLines(copy), stripped };
  }

  stripped = true;
  while (copy.length > 0) {
    const line = copy[0];
    if (line.startsWith('>') || line.trim() === '') {
      copy.shift();
      continue;
    }
    break;
  }

  copy = stripLeadingBlankLines(copy);
  return { lines: stripTrailingBlankLines(copy), stripped };
}

function parseMetadata(lines: string[], fallbackTitle: string): ClaudeExporterJson['metadata'] {
  const titleLine = lines.find(line => line.startsWith('# '));
  const metadata: ClaudeExporterJson['metadata'] = {
    title: titleLine ? titleLine.replace(/^#\s+/, '').trim() : fallbackTitle,
    dates: {}
  };

  for (const line of lines) {
    const metaMatch = line.match(META_RE);
    if (metaMatch) {
      const key = metaMatch[1].toLowerCase() as 'created' | 'updated' | 'exported';
      metadata.dates[key] = metaMatch[2].trim();
      continue;
    }

    const linkMatch = line.match(LINK_RE);
    if (linkMatch) {
      metadata.link = (linkMatch[2] || linkMatch[1] || linkMatch[3] || '').trim();
      continue;
    }

    const footerMatch = line.match(FOOTER_RE);
    if (footerMatch) {
      metadata.powered_by = footerMatch[1];
    }
  }

  return metadata;
}

function extractTimestampAndBody(sectionLines: string[]): { time: string; bodyLines: string[] } {
  const lines = [...sectionLines];
  while (lines.length > 0 && lines[0].trim() === '') lines.shift();

  let time = '';
  if (lines[0]?.startsWith('>')) {
    time = stripBlockquoteMarker(lines.shift() || '').trim();
  }

  while (lines.length > 0 && lines[0].trim() === '') lines.shift();
  return { time, bodyLines: lines };
}

function removeFooterFromFinalSection(sections: ParsedSection[], metadata: ClaudeExporterJson['metadata']): void {
  const last = sections[sections.length - 1];
  if (!last) return;

  const body = stripTrailingBlankLines(last.bodyLines);
  const footerLine = body[body.length - 1]?.trim();
  const footerMatch = footerLine?.match(FOOTER_RE);
  if (!footerMatch) {
    last.bodyLines = body;
    return;
  }

  metadata.powered_by = footerMatch[1];
  body.pop();
  last.bodyLines = stripTrailingBlankLines(body);
}

function parseSections(lines: string[], metadata: ClaudeExporterJson['metadata']): ParsedSection[] {
  const sections: ParsedSection[] = [];
  let currentLabel: 'User' | 'Assistant' | undefined;
  let currentLines: string[] = [];

  function flush(): void {
    if (!currentLabel) return;

    const { time, bodyLines } = extractTimestampAndBody(currentLines);
    let strippedThinking = false;
    let finalBodyLines = stripTrailingBlankLines(bodyLines);

    if (currentLabel === 'Assistant') {
      const stripped = stripAssistantThinking(finalBodyLines);
      finalBodyLines = stripped.lines;
      strippedThinking = stripped.stripped;
    }

    sections.push({
      label: currentLabel,
      role: currentLabel === 'User' ? 'human' : 'assistant',
      time,
      bodyLines: finalBodyLines,
      strippedThinking
    });
  }

  for (const line of lines) {
    const sectionMatch = line.match(SECTION_RE);
    if (sectionMatch) {
      flush();
      currentLabel = sectionMatch[1] as 'User' | 'Assistant';
      currentLines = [];
    } else if (currentLabel) {
      currentLines.push(line);
    }
  }
  flush();

  removeFooterFromFinalSection(sections, metadata);
  return sections;
}

function parseClaudeExporterMarkdown(markdown: string, fallbackTitle: string): ClaudeExporterJson {
  const lines = markdown.replace(/\r\n/g, '\n').replace(/\r/g, '\n').split('\n');
  const metadata = parseMetadata(lines, fallbackTitle);
  const sections = parseSections(lines, metadata);
  const strippedCount = sections.filter(section => section.strippedThinking).length;

  metadata.cleaned = {
    source_format: 'claude_exporter_markdown',
    stripped_assistant_thinking_blocks: strippedCount,
    notes: [
      'Message bodies were reconstructed from Markdown rather than paired JSON.',
      'Leading assistant blockquote blocks were treated as thinking summaries and stripped.',
      'Trailing Claude Exporter footer was treated as metadata, not message content.'
    ]
  };

  const messages = sections.map((section, index) => {
    const say = section.bodyLines.join('\n').trim();
    if (section.role === 'assistant' && say === '') {
      process.stderr.write(`warning: assistant message ${index} (${section.time || 'no timestamp'}) has no visible content after stripping thinking\n`);
    }
    return { role: section.role, time: section.time, say };
  });

  return { metadata, messages };
}

function main(): void {
  const { inputPath, outputPath } = parseArgs(process.argv.slice(2));
  const markdown = readFileSync(inputPath, 'utf8');
  const output = parseClaudeExporterMarkdown(markdown, basename(inputPath, '.md'));
  const json = JSON.stringify(output, null, 2) + '\n';

  if (outputPath) {
    writeFileSync(outputPath, json);
  } else {
    process.stdout.write(json);
  }
}

main();
